trigger:
  branches:
    include:
      - main # Adjust if your default branch is named differently

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "7.x" # Use the latest version of the .NET SDK

  - script: |
      docker build -t $(DockerRegistryServiceConnection)/dentalpracticeproject:$(Build.BuildId) .
    displayName: "Build Docker Image"

  - task: Docker@2
    inputs:
      command: "push"
      containerRegistry: "$(DockerRegistryServiceConnection)"
      repository: "dentalpracticeproject"
      tags: |
        $(Build.BuildId)
    displayName: "Push Docker Image"
