trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      versionSpec: "8.x"
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet restore DentistAppointmentSystem/DentistAppointmentSystem.csproj
    displayName: "Restore dependencies"

  - script: dotnet build DentistAppointmentSystem/DentistAppointmentSystem.csproj --configuration Release
    displayName: "Build project"

  - script: dotnet test DentistAppointmentSystem.Tests/DentistAppointmentSystem.Tests.csproj --configuration Release
    displayName: "Run tests"

  - task: Docker@2
    inputs:
      command: "build"
      containerRegistry: "DockerHubConnection"
      repository: "olehcollins/dentalpracticeproject"
      dockerfile: "**/Dockerfile"
      tags: "latest"
    displayName: "Build Docker image"

  - task: Docker@2
    inputs:
      command: "push"
      containerRegistry: "DockerHubConnection"
      repository: "olehcollins/dentalpracticeproject"
      tags: "latest"
    displayName: "Push Docker image to Docker Hub"
