trigger:
  branches:
    include:
      - main # Adjust if your default branch is named differently

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "7.x" # Use the latest version of the .NET SDK

  - script: |
      docker build -t olehcollins/dentalpracticeproject:$(Build.BuildId) .
    displayName: "Build Docker Image"

  - script: |
      docker images
    displayName: "List Docker Images"

  - task: Docker@2
    inputs:
      command: "push"
      containerRegistry: "DockerHubServiceConnection" # Name of the service connection
      repository: "olehcollins/dentalpracticeproject" # DockerHub repository name
      tags: |
        $(Build.BuildId)
    displayName: "Push Docker Image"
